### ISSUE TITLE
Example in readme - (selectedItem: string) -> (selectedItem)

### ISSUE THREAD

**Issue by sr57** [prabhuignoto/vue-float-menu#15]
Example in readme ( https://github.com/prabhuignoto/vue-float-menu#-getting-started )

//    const handleSelection = (selectedItem: string) => {
    const handleSelection = (selectedItem) => {

tested with vue@3.0.3

**Comment by prabhuignoto** [comment]
thanks for reporting. please feel free to open a PR if you have tested/verified it.

**Comment by sr57** [comment]
HI, 

I've tested it, it works, but I don't know how tu use Git(hub) and I did not find the way to send a PR. 

Currently, I'm working on a script to setup a Laravel project automatically, (have already done the basement, the automatic CRUD for every tables defined in a setup db, a menu without the use of Vue.js) and I'll work to setup your menu if Vue is chosen as ui with Laravel. 

I should put this project on git... but it's in my todo list for 3 reasons : 
1) probably I'll choose Framagit (Gitlab) and not Github 
2) have to learn and review the 2 solutions to decide what to do 
3) translate everything from to english 

That's said, thanks for 'vue-menu-float', it's a very good tool. 

Regards. 



De: "Prabhu Murthy" <notifications@github.com> 
À: "prabhuignoto/vue-float-menu" <vue-float-menu@noreply.github.com> 
Cc: "sr57" <sr57@gmx.com>, "Author" <author@noreply.github.com> 
Envoyé: Vendredi 27 Novembre 2020 13:46:43 
Objet: Re: [prabhuignoto/vue-float-menu] Example in readme - (selectedItem: string) -> (selectedItem) (#15) 





thanks for reporting. please feel free to open a PR if you have tested/verified it.
